// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tur_agen_asp_net.Models;

#nullable disable

namespace Tur_agen_asp_net.Migrations
{
    [DbContext(typeof(ApDbContext))]
    [Migration("20231012164946_InitialTurAgency")]
    partial class InitialTurAgency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tur_agen_asp_net.Models.Tour", b =>
                {
                    b.Property<int>("id_tour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tour"));

                    b.Property<int>("TCount")
                        .HasColumnType("int");

                    b.Property<string>("TCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TName_tour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TTown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tour");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.TourOrder", b =>
                {
                    b.Property<int>("id_tour_oder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tour_oder"));

                    b.Property<int>("TOCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TOSumm")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("Tourid_tour")
                        .HasColumnType("int");

                    b.Property<int>("id_tour")
                        .HasColumnType("int");

                    b.Property<int>("id_users")
                        .HasColumnType("int");

                    b.HasKey("id_tour_oder");

                    b.HasIndex("Tourid_tour");

                    b.HasIndex("id_tour");

                    b.HasIndex("id_users");

                    b.ToTable("TourOrders");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.Users", b =>
                {
                    b.Property<int>("id_users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_users"));

                    b.Property<string>("UEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ULogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UPhone")
                        .HasColumnType("int");

                    b.Property<string>("USurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.TourOrder", b =>
                {
                    b.HasOne("Tur_agen_asp_net.Models.Tour", null)
                        .WithMany("TourOrders")
                        .HasForeignKey("Tourid_tour");

                    b.HasOne("Tur_agen_asp_net.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("id_tour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tur_agen_asp_net.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.Tour", b =>
                {
                    b.Navigation("TourOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
