// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tur_agen_asp_net.Models;

#nullable disable

namespace Tur_agen_asp_net.Migrations
{
    [DbContext(typeof(ApDbContext))]
    partial class ApDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tur_agen_asp_net.Models.Tour", b =>
                {
                    b.Property<int>("id_tour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tour"));

                    b.Property<int>("TCount")
                        .HasColumnType("int");

                    b.Property<string>("TCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TName_tour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TTown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tour");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.TourOrder", b =>
                {
                    b.Property<int>("id_tour_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tour_order"));

                    b.Property<decimal>("TOPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TOQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("id_tour_order");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("TourOrder");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.UserOrderHistory", b =>
                {
                    b.Property<int>("id_user_order_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_user_order_history"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("id_user_order_history");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrderHistory");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.Users", b =>
                {
                    b.Property<int>("id_users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_users"));

                    b.Property<string>("UEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UIsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("ULogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UPhone")
                        .HasColumnType("int");

                    b.Property<string>("USurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_users");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.TourOrder", b =>
                {
                    b.HasOne("Tur_agen_asp_net.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tur_agen_asp_net.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tur_agen_asp_net.Models.UserOrderHistory", b =>
                {
                    b.HasOne("Tur_agen_asp_net.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tur_agen_asp_net.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
